# Generated by Django 4.0.1 on 2022-04-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_band_year_formed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('sold', models.BooleanField(default=0)),
                ('type', models.CharField(choices=[('RC', 'Records'), ('CLOTH', 'Clothing'), ('POST', 'Posters'), ('MISC', 'Miscellaneous')], max_length=10)),
            ],
        ),
    ]
