# Generated by Django 4.0.1 on 2022-04-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listings_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.artist'),
        ),
    ]
